samples: config/samples.tsv

alevin:
  # transcript to gene map tsv file (--tgMap)
  tgmap: /ifs/mirror/alevin/txp2gene.tsv
  # Selective alignment index
  sa_index: /ifs/mirror/alevin/salmon_partial_sa_index
  # ADT index
  adt_index: /ifs/mirror/alevin/adt_index
  # HTO index
  hto_index: /ifs/mirror/alevin/hto_index
  # starting index of the feature barcode on Read2 (--featureStart)
  feature_start: 0
  # length of the feature barcode (--featureLength)
  feature_length: 15
  # close upper bound on expected number of cells (--expectCells)
  expect_cells: 35000
  # Cell-Barcodes end (5 or 3) location (--end)
  end: 5
  # umi length parameter for unknown protocol (--umiLength)
  umi_length: 10
  # barcode length parameter for unknown protocol(--barcodeLength)
  barcode_length: 16
  # resources
  threads: 16
  memory_gb: 20
